# Generated by Django 3.0.2 on 2020-01-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_highlightedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageslot',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
